---
title: "EPG_Data_Analysis"
author: "Beery Yakov, Daniel Kunk, Vamsi Nalam"
date: '2022-09-29'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Code from Beery Yakov to calculate parameter information from .ANA files
options(stingsAsFactors = FALSE, digits = 2, scipen = 3)

waveform_labels = c("np" = 1,
                    "C" = 2,
                    "E1e" = 3,
                    "E1" = 4,
                    "E2" = 5,
                    "F" = 6,
                    "G" = 7,
                    "pd-S" = 8,
                    "pd-S-II-2" = 9,
                    "pd-S-II-3" = 10,
                    "pd-L" = 11,
                    "pd-L-II-2" = 13,
                    "pd-L-II-3" = 14,
                    "end" = 12)

if(!interactive()){
  #Non-interactive
  library(R.utils)
  args = R.utils::commandArgs(trailingOnly = TRUE,asValues = TRUE)
  
  #Import .ANA file witj -- input /path/EPG.ANA
  EPG_analysis = read.delim(file = args[["input"]], header = FALSE, fileEncoding = "UTF-16LE", col.names = c("Waveform", "Time", "mV"))
  
  #Manually specify labels (e.g. --C 5 --np 7)
  for(wave_change in names(args)[names(args) %in% names(waveform_labels)]){
    waveform_labels[wave_change] = args[wave_change]
  }
}else{
  #Interactive
    EPG_analysis = read.delim(file = file.choose(), header = FALSE, fileEncoding = "UTF-16LE", col.names = c("Waveform", "Time", "mV"))
}

#Parameter function
EPG_calc = function(EPG_analysis){

EPG_parameters = as.data.frame(matrix(nrow = 0, ncol = 2, dimnames = list(NULL,c("Value", "Descrption"))))

#Some precomputed values for convenience
  
}
}
  }
}

```

```{r}
library(tidyverse)
library(plotrix)
#The plotrix package allows for calculating Standard error
library(kableExtra)
#kableExtra to create tables
library(dplyr)

epgdata = read_csv('24hrLD_8hr_0_12zt_format_subset.csv')

```

```{r}
# Summary Statistics!

sumstat_mean = epgdata %>%
  group_by(Treat) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE, round(1))

sumstat_sd = epgdata %>% 
 group_by(Treat) %>% 
 summarise_if(is.numeric, sd, na.rm = TRUE)

#sumstat_med = epgdata %>% 
#  group_by(Treat) %>% 
#  summarise_if(is.numeric, median, na.rm = TRUE, round(1))

#sumstat_IQR = epgdata %>%
#  group_by(Treat) %>%
#  summarise_if(is.numeric, IQR, na.rm = TRUE, round(1))

sumstat_std.error = epgdata %>%
  group_by(Treat) %>%
  summarise_if(is.numeric, std.error, na.rm = TRUE)

sumstat = epgdata %>%
  group_by(Treat) %>% 
  summarise_if(is.numeric, funs(mean,sd,std.error), na.rm = TRUE)

```

```{r}
#Write a table of results

#write_csv()

#Combine mean, standard error etc into a table

mean = t(sumstat_mean)
sem = t(sumstat_std.error)

mean_sem = merge(mean, sem, by = 'row.names', all = TRUE)
colnames(mean_sem) = c("Parameters", "Zt0_mean", "ZT12_mean", "Zt0_SEM", "Zt12_SEM")
relocate(mean_sem, ZT12_mean, .after=Zt0_SEM)
write_csv(mean_sem, "24hLD_0_12zt_results.csv")

```

```{r}
Wilcox_epgdata_bygroup <- lapply(2:32, function(x) pairwise.wilcox.test(epgdata[[x]], epgdata$Treat, paired = F, p.adjust.method = NULL))
names(Wilcox_epgdata_bygroup) <- names(epgdata)[2:32]
Wilcox_epgdata_bygroup


sapply(Wilcox_epgdata_bygroup, function(x) {
    p <- x$p.value
    n <- outer(rownames(p), colnames(p), paste, sep='v')
    p <- as.vector(p)
    names(p) <- n
    p
})
```

```{r}
# Data frames by individual group comparison. 

zt0zt12 = read_csv("24LD_8hour_0zt_12zt.csv")

zt8zt20 = read_csv("24LD_8hour_8zt_20zt.csv")

zt0zt8zt16 = read_csv("24LD_8hr_0zt_8zt_16zt.csv")

zt4zt16 = read_csv("24LD_8hr_0zt_8zt_16zt.csv")
```

```{r}
# 0zt vs 12zt
Wilcox_epgdata_0zt_12zt <- lapply(3:47, function(x) pairwise.wilcox.test(zt0zt12[[x]], zt0zt12$Treat, paired = F, p.adjust.method = NULL))
names(Wilcox_epgdata_0zt_12zt) <- names(zt0zt12)[3:47]
Wilcox_epgdata_0zt_12zt
```

```{r}
# 0zt vs 8zt vs 16zt 
Wilcox_epgdata_0zt_8zt_16zt <- lapply(3:47, function(x) pairwise.wilcox.test(zt0zt8zt16[[x]], zt0zt8zt16$Treat, paired = F, p.adjust.method = NULL))
names(Wilcox_epgdata_0zt_8zt_16zt) <- names(zt0zt8zt16)[3:47]
Wilcox_epgdata_0zt_8zt_16zt
```

```{r}
# 4zt vs 16zt 
Wilcox_epgdata_4zt_16zt <- lapply(3:47, function(x) pairwise.wilcox.test(zt4zt16[[x]], zt4zt16$Treat, paired = F, p.adjust.method = NULL))
names(Wilcox_epgdata_4zt_16zt) <- names(zt4zt16)[3:47]
Wilcox_epgdata_4zt_16zt
```



```{r}
# 8zt vs 20zt
Wilcox_epgdata_8zt_20zt <- lapply(3:47, function(x) pairwise.wilcox.test(zt8zt20[[x]], zt8zt20$Treat, paired = F, p.adjust.method = NULL))
names(Wilcox_epgdata_8zt_20zt) <- names(zt8zt20)[3:47]
Wilcox_epgdata_8zt_20zt
```





