#' Calculate and Plot Empirical Proportions of EPG Waveforms Over Time
#'
#' @description 
#' A modification of the original `discoEPG::ana_to_timeseries` function. Instead of 
#' returning the single most frequent waveform (mode) across all recordings at each second, 
#' this function calculates the empirical probability (proportion) of all active insects 
#' engaging in each specific behavior over continuous time. It then generates a continuous 
#' GAM-smoothed visualization of these behavioral shifts. This is particularly useful for 
#' summarizing longitudinal or circadian feeding behaviors (e.g., across 24h recordings).
#' 
#' @author Daniel Kunk
#'
#' @param ana_df Data frame; the combined EPG data output generated by `combine_ana()`.
#' @param waveform_labels Named numeric vector; maps waveform integer codes to character labels.
#' 
#' @return A list of length 2 containing:
#' \describe{
#'   \item{data}{A long-format data frame containing the second-by-second counts and proportions for each waveform.}
#'   \item{plot}{A `ggplot2` object displaying the smoothed empirical proportions over time in hours.}
#' }
#' 
#' @import tidyverse
#' @import ggplot2
#' 
#' @export
ana_to_timeseries_proportion = function(ana_df, waveform_labels) {
  # make a list of data split by filename
  ana_df_list = split(ana_df, ana_df$filename)
  
  # quick data check to see if recs are same length
  maxTimes = sapply(ana_df_list, function(df) max(df$Time))
  if(length(unique(maxTimes)) > 1) stop("STOP!!! .ANA files differ in duration!")
  
  # expand the data to second by second format.
  expandDatList = lapply(ana_df_list, function(df) {
    dfExpand = data.frame(Time = 0:max(df$Time), Waveform = integer(length = length(0:max(df$Time))))
    for(i in 1:(nrow(df)-1)) {
      ind = dfExpand$Time >= df$Time[i] & dfExpand$Time < df$Time[i+1]
      dfExpand$Waveform[ind] = df$Waveform[i]
    }
    # fill in last row with '12' (end)
    dfExpand$Waveform[nrow(dfExpand)] = 12
    return(dfExpand$Waveform)
  })
  
  # Matrix of waveforms for each second. Rows=seconds, Columns=files.
  expandMat = do.call(cbind, expandDatList)
  
  # Combine E1/E1e (relabel as waveform = 888)
  idx_E = waveform_labels[names(waveform_labels) %in% c('E1', 'E1e')]
  expandMat[expandMat %in% idx_E] = 888
  # Combine all "pd" phases (relabel as waveform = 999)
  idx_pd = waveform_labels[names(waveform_labels) %in% c('pd-S', 'pd-S-II-2', 'pd-S-II-3', 'pd-L', 'pd-L-II-2', 'pd-L-II-3')]
  expandMat[expandMat %in% idx_pd] = 999
  
  # Rebuild waveform_labels
  waveform_labels = waveform_labels[!names(waveform_labels) %in% c('E1', 'E1e', 'pd-S', 'pd-S-II-2', 'pd-S-II-3', 'pd-L', 'pd-L-II-2', 'pd-L-II-3')]
  waveform_labels = c(waveform_labels, c('E1' = 888, 'pd' = 999))
  
  # Old behavior above, new behavior below...
  # Convert matrix to dataframe and add time column
  expand_df = as.data.frame(expandMat)
  expand_df$time = 1:nrow(expand_df)
  
  # Pivot to long format to calculate grouped proportions safely
  propDat = expand_df %>%
    pivot_longer(cols = -time, names_to = "filename", values_to = "waveform_mode") %>%
    
    # Map the waveform codes back to their character labels
    mutate(activity = as.character(names(waveform_labels)[match(waveform_mode, waveform_labels)])) %>%
    
    # Count how many insects are doing each activity at each second
    group_by(time, activity) %>%
    summarise(count = n(), .groups = "drop") %>%
    
    # Force missing time/activity combinations to have a count of 0 
    tidyr::complete(time, activity, fill = list(count = 0)) %>%
    
    # Calculate the proportion (count / total active insects at that second)
    group_by(time) %>%
    mutate(proportion = count / sum(count)) %>%
    ungroup() %>%
    
    # Add an hours column for cleaner plotting down the line
    mutate(hours = time / 3600)
  
  # Re-order factors to match waveform_labels (like original discoEPG logic)
  propDat$activity = factor(toupper(propDat$activity),
                            levels = toupper(intersect(names(waveform_labels), unique(propDat$activity))))
  
  # Remove 'END' before plotting and drop the phantom factor level
  plotDat = subset(propDat, activity != 'END')
  plotDat$activity = droplevels(plotDat$activity)
  
  # Generate smoothed time series plot
  ts_plot = ggplot(plotDat, aes(x = hours, y = proportion, color = activity)) +
    stat_smooth(method = "gam", formula = y ~ s(x, bs = "cs", k = 15), se = TRUE, linewidth = 2, alpha = 0.2) +
    theme_classic() +
    coord_cartesian(xlim = c(0, max(plotDat$hours, na.rm = TRUE))) +
    scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
    labs(x = "Time (hours)", y = "Proportion of Insects") + 
    scale_color_manual(
      values = scales::alpha(c("#9e0142", "#d53e4f", "#f46d43", "#fdae61", "#abdda4", "#66c2a5", "#3288bd"), 0.6), 
      breaks = c('NP', 'C', 'PD', 'E1', 'E2', 'F', 'G'), 
      drop = TRUE
    )
  
  return(list(data = propDat, plot = ts_plot))
}
